version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d