name: build and test

on:
  pull_request:
    branches:
      - release/*
      - master
jobs:
  build-and-test-for-beta:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SBT
        run: sbt update

      - name: Run Scalafix
        run: sbt "scalafixAll --check"

      - name: Run tests
        run: sbt test

      - name: coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/scala-2.13/scoverage-report/scoverage.xml
          fail_ci_if_error: true

